[project]
name = "ass1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bs4>=0.0.2",
    "pymongo>=4.11.2",
    "requests>=2.32.3",
    "selenium>=4.29.0",
    "wikipedia>=1.4.0",
]
